### ISSUE TITLE
false violations

### ISSUE THREAD

**Issue by marcelloh** [resotto/gochk#6]
when I have a violation, it would be good to see if there is a usage of that inside the complete source-file
Like:
I use an import "myProg/infrastructure/db" inside a lower ring "interfaces", but it is only in use by injection, which is no violation.
if there is a command like "db.whatsoever", then it is a violation.
Of course, when the import has an alias, check on the alias usage directly.

**Comment by resotto** [comment]
@marcelloh Thank you for your comment.
You mean I should fix the error message when violations occured?

I think this should be fixed in order not to violate The Dependency Rule of Clean Architecture, which means the injection of "myProg/infrastructure/db" should be placed in the lower ring(circle) "interfaces".
> I use an import "myProg/infrastructure/db" inside a lower ring "interfaces", but it is only in use by injection, which is no violation.

About false positive, you can ignore without `-e=true` flag.
> In this phase, you can use Gochk with -e=true which means Gochk fails with exit code 1 when violations occur. So you can detect violations thoroughly and keep codes clean.

**Comment by resotto** [comment]
@marcelloh If you have any updates, please reopen this.
